name: Docker Build and Push

on:
  push:
    branches:
      - ejazGraphGateway

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          dcr.360hkm.info:5050/heliosip/heliosip/slpower:latest
          your-dockerhub-username/your-repo-name:${{ github.sha }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}